### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './qt_opt_model/model3' Terminated

### ISSUE THREAD

**Issue by AshWYL** [quantumiracle/QT_Opt#2]
Hi, When I execute "qt_opt_v3.py", got FileNotFoundError:
Traceback (most recent call last):
  File "/home/ashwang/Hellow python world/Pytorch/QT_Opt-master/qt_opt_v3.py", line 360, in <module>
    qt_opt.load_model(model_path)
  File "/home/ashwang/Hellow python world/Pytorch/QT_Opt-master/qt_opt_v3.py", line 267, in load_model
    self.qnet.load_state_dict(torch.load(path))
  File "/home/ashwang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './qt_opt_model/model3'

There is nothing about "/qt_opt_model/model3" in your code or datasets. Could you explain this to me? Thank you very much!

**Comment by WaYiCh** [comment]
you need create a folder named as qt_opt_model in your current directory.
```
cd QT_Opt
mkdir qt_opt_model
python qt_opt_v2.py --train
```
